version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cms_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: password
    volumes:
      - proj_green_careers_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "directus"]
      interval: 5s
      timeout: 5s
      retries: 5

  directus:
    image: directus/directus:11.10.2
    container_name: directus
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8055:8055"
    environment:
      SECRET: "proj-green-careers"
      ADMIN_EMAIL: "admin@local.dev"
      ADMIN_PASSWORD: "password"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "password"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: true
      CORS_ORIGIN: "http://localhost:4000"
    volumes:
      - proj_green_careers_directus_data:/directus/uploads
      - proj_green_careers_directus_data:/directus/extensions

volumes:
  proj_green_careers_postgres_data:
  proj_green_careers_directus_data: